[package]
name = "rcpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Unfortunatelly, right now lalrpop has some minnor issues that I needed to patch out
[build-dependencies]
lalrpop = {version = "0.19.8", path = "../lalrpop/lalrpop"}

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }
lazy-regex = "2.3.0"
subslice_index = "0.5.0"
regex = "1.0.0"
onig = "6"
lazy_static = "1.4.0"
logos = "0.12.1"
colored = "2.0.0"
lalrpop-util = {version = "0.19.8", path = "../lalrpop/lalrpop-util"}
log = "0.4.17"
env_logger = "0.9.0"
test-log = "0.2.10"
multiset = "0.0.5"